### ISSUE TITLE
Repositories are not being pulled from the branch specified in ProjectsTags.cmake

### ISSUE THREAD

**Issue by jeljaik** [robotology/codyco-superbuild#42]
When you switch to the branch `new_wbi_ID` in `codyco-supebuild` for example, if you wanna get certain repositories from their `new_wbi_ID` branch, you're supposed to define a tag in `ProjectsTags.cmake` as `set(wholeBodyInterface_TAG new_wbi_ID)`. What I expect is that after making these changes, doing `make update-all` will pull all these repos from their `new_wbi_ID` branch. However, this is not the case. They are all pulled from their `master` branch and then you're forced to switch branch in each repository independently.

**Comment by traversaro** [comment]
This is still a major pain point in using the superbuild. The `vcstool` solved it in case all the subprojects has the same branch in https://github.com/vcstools/wstool/pull/55 . Closing the issue here, but it may be worth to open a corresponding issue in ycm to track it as it is a classical user complaint about the superbuild.
