### ISSUE TITLE
Removing excessive amount of associated warnings

### ISSUE THREAD

**Issue by jeljaik** [robotology/codyco-superbuild#87]
For some people it might be annoying to get the excessive amount of warnings of the associated projects  (Yarp, iCub, etc) during compilation... I remember there was a way to suppress them. @francesco-romano?

**Comment by francesco-romano** [comment]
This is more single-project-related as warnings should in general be fixed instead of being suppressed.

Anyway, one way (which IMHO is also the correct way) is to use the `include_directory(SYSTEM dir)` cmake command (but I don't know if this applies also to imported target @traversaro ).
Note that Xcode does not support this, so if you compile the generated Xcode project you will see the warnings.

Also, starting from Xcode8 there is a `-quiet` flag which suppresses most of the output (but I think that warnings are printed anyway, but at least you save all those `CompileC` lines..)
